default_platform(:ios)

# use_keychain(true) # credentials_manager 사용 설정


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    unlock_keychain(
      path: "login.keychain-db",
      password: "3325",
      set_default: true
    )
    # setup_ci
    
    # match는 appstore 타입으로 실행됨
    match(type: "appstore")

    # 빌드 번호 증가
    increment_build_number(xcodeproj: "stepin.xcodeproj")

    # 앱 빌드
    build_app(
      workspace: "stepin.xcworkspace",
      scheme: "stepin"
    )
    
    # TestFlight에 업로드
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
