default_platform(:ios)

# use_keychain(true) # credentials_manager 사용 설정


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci # if ENV['CI']

    # match는 appstore 타입으로 실행됨
    match(type: "appstore")

    # 빌드 번호 증가
    increment_build_number(xcodeproj: "stepin.xcodeproj")

    # 앱 빌드
    build_app(
      workspace: "stepin.xcworkspace",
      scheme: "stepin"
    )

    # TestFlight에 업로드
    upload_to_testflight(username: username, password: password)
  end
end
