name: Build and Test iOS App and Deploy to TestFlight

on:
  push:
    branches:
      - stage

jobs:
  build_and_deploy:
    name: Build, Test, and Deploy to TestFlight
    runs-on: macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Gem install
        run: gem install cocoapods

      - name: Pod install
        run: pod install

        
      - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'beta'