name: Build and Test iOS App and Deploy to TestFlight

on:
  push:
    branches:
      - stage

jobs:
  build_and_deploy:
    name: Build, Test, and Deploy to TestFlight
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: bundle lock --add-platform x86_64-darwin-20

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Gem install Cocoapodss
        run: gem install cocoapods

      - name: Pod install
        run: pod install
        
      - name: Generate Keystore file from Github Secrets
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > ./gc_keys.json

        
      - uses: maierj/fastlane-action@v3.0.0
      - run: fastlane beta